# Generated by Django 3.0.1 on 2020-02-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200225_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishDay',
            field=models.DateField(auto_now=True),
        ),
    ]
